### ISSUE TITLE
`Not pulling components because this project is not configured with the "react" framework` prints before and after push

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-codegen-ui#934] opened 2023-02-22 01:22 UTC
### How did you install the Amplify CLI?

pnpm

### If applicable, what version of Node.js are you using?

18

### Amplify CLI Version

11.0.0-beta.7

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

n/a

### Describe the bug

The message in the title and noted below appears both before and after push, which is a small Amplify project without Studio enabled

```
Not pulling components because this project is not configured with the "react" framework.
```

<details><summary>full logs</summary>

```
➜  ay push --allow-destructive-graphql-schema-updates --yes --debug
Not pulling components because this project is not configured with the "react" framework.
⠏ Fetching updates to backend environment: dev from the cloud.Overrides functionality is not implemented for this category
⠴ Fetching updates to backend environment: dev from the cloud.
⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types:
	 - Todo2
Learn more about "@auth" authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
⠦ Fetching updates to backend environment: dev from the cloud.Be careful when using @auth directives on a field in a root type. @auth directives on field definitions use the source object to perform authorization logic and the source will be an empty object for fields on root types. Static group authorization should perform as expected.
⠧ Fetching updates to backend environment: dev from the cloud.✅ GraphQL schema compiled successfully.

Edit your schema at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema.graphql or place .graphql files in a directory at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema
Overrides functionality is not implemented for this category
✔ Successfully pulled backend environment dev from the cloud.
⠹ Building resource api/a1268
⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types:
	 - Todo2
Learn more about "@auth" authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
Be careful when using @auth directives on a field in a root type. @auth directives on field definitions use the source object to perform authorization logic and the source will be an empty object for fields on root types. Static group authorization should perform as expected.
⠸ Building resource api/a1268✅ GraphQL schema compiled successfully.

Edit your schema at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema.graphql or place .graphql files in a directory at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema

    Current Environment: dev
    
┌──────────┬────────────────┬───────────┬───────────────────┐
│ Category │ Resource name  │ Operation │ Provider plugin   │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Auth     │ a12682544f6a9  │ Create    │ awscloudformation │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Api      │ a1268          │ Update    │ awscloudformation │
├──────────┼────────────────┼───────────┼───────────────────┤
│ Hosting  │ amplifyhosting │ No Change │                   │
└──────────┴────────────────┴───────────┴───────────────────┘

⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types:
	 - Todo2
Learn more about "@auth" authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
Be careful when using @auth directives on a field in a root type. @auth directives on field definitions use the source object to perform authorization logic and the source will be an empty object for fields on root types. Static group authorization should perform as expected.
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema.graphql or place .graphql files in a directory at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema
⠼ Building resource api/a1268
⚠️  WARNING: Some types do not have authorization rules configured. That means all create, read, update, and delete operations are denied on these types:
	 - Todo2
Learn more about "@auth" authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
⠴ Building resource api/a1268Be careful when using @auth directives on a field in a root type. @auth directives on field definitions use the source object to perform authorization logic and the source will be an empty object for fields on root types. Static group authorization should perform as expected.
⠦ Building resource api/a1268✅ GraphQL schema compiled successfully.

Edit your schema at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema.graphql or place .graphql files in a directory at /Users/josef/Documents/projects/aws-amplify/reproductions/a1268/amplify/backend/api/a1268/schema

Deployment completed.
Deploying root stack a1268 [ ====================-------------------- ] 2/4
	amplify-a1268-dev-155611       AWS::CloudFormation::Stack     UPDATE_COMPLETE_C
	autha12682544f6a9              AWS::CloudFormation::Stack     CREATE_COMPLETE  
	apia1268                       AWS::CloudFormation::Stack     UPDATE_COMPLETE  
Deployed api a1268 [ ======================================== ] 9/9
	GraphQLAPI                     AWS::AppSync::GraphQLApi       UPDATE_COMPLETE  
	GraphQLAPITransformerSchema3C… AWS::AppSync::GraphQLSchema    UPDATE_COMPLETE  
	GraphQLAPIDefaultApiKey215A6D… AWS::AppSync::ApiKey           UPDATE_COMPLETE  
	QueryHelloDataResolverFnQuery… AWS::AppSync::FunctionConfigu… CREATE_COMPLETE  
	Todo                           AWS::CloudFormation::Stack     UPDATE_COMPLETE  
	QueryhelloResolver             AWS::AppSync::Resolver         CREATE_COMPLETE  
	Todo2                          AWS::CloudFormation::Stack     UPDATE_IN_PROGRES
Deployed auth a12682544f6a9 [ ======================================== ] 10/10
	UserPool                       AWS::Cognito::UserPool         CREATE_COMPLETE  
	UserPoolClient                 AWS::Cognito::UserPoolClient   CREATE_COMPLETE  
	UserPoolClientWeb              AWS::Cognito::UserPoolClient   CREATE_COMPLETE  
	UserPoolClientRole             AWS::IAM::Role                 CREATE_COMPLETE  
	UserPoolClientLambda           AWS::Lambda::Function          CREATE_COMPLETE  
	UserPoolClientLambdaPolicy     AWS::IAM::Policy               CREATE_COMPLETE  
	UserPoolClientLogPolicy        AWS::IAM::Policy               CREATE_COMPLETE  
	UserPoolClientInputs           Custom::LambdaCallout          CREATE_COMPLETE  
	IdentityPool                   AWS::Cognito::IdentityPool     CREATE_COMPLETE  
	IdentityPoolRoleMap            AWS::Cognito::IdentityPoolRol… CREATE_COMPLETE  

Deployment state saved successfully.

GraphQL endpoint: https://mifc66khtzg7tcrmlio422kz2u.appsync-api.us-east-1.amazonaws.com/graphql
GraphQL API KEY: da2-54qsjoh6zbge3mfad4gypm34ta

GraphQL transformer version: 2

Not pulling components because this project is not configured with the "react" framework.

```

</details>

### Expected behavior

this message does not print unless this project has Studio enabled or I am expecting to pull components (/attempt to).

### Reproduction steps

1. create an Amplify project with `amplify init -y`
2. create a GraphQL API `amplify add api` > GraphQL
4. push with `amplify push -y`
5. push to git and add Hosting with `amplify add hosting`
6. let hosting build, run `amplify pull`
7. try to make a change in your schema and push

### Project Identifier

6eb2e5ca4610f067a938060bf5ef796a

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by alharris-at** [comment] 2023-02-28 00:19
This is coming from the util-uibuilder package in CLI https://github.com/aws-amplify/amplify-cli/blob/7dc9179e6e15e1a261bcb717ec0e777f6f3dd68c/packages/amplify-util-uibuilder/src/commands/utils/shouldRenderComponents.ts#L37-L40 but transferring to the codegen ui repo since the studio ui team probably owns whatever fix this requires.

**Comment by cwoolum** [comment] 2024-05-08 01:17
This message only appears when debugging is enabled and is there on purpose. Component generation is opt-out, not opt-in. I'm going to close this since it works as intended.

**Closed by cwoolum** 2024-05-08 01:17 UTC
